name       : libmodplug
homepage   : http://modplug-xmms.sourceforge.net/
version    : 0.8.9.0
release    : 5
source     :
    - https://sourceforge.net/projects/modplug-xmms/files/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz : 457ca5a6c179656d66c01505c0d95fafaead4329b9dbaa0f997d00a3508ad9de
license    : PDDL-1.0
summary    : Library for playing MOD-like music files
component  : multimedia.library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
description: |
    libmodplug is a library based on the mod rendering code from
    ModPlug, a popular windows mod player written by Olivier Lapicque
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-lie-about-includedir-location.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        linux32 %configure --disable-static --prefix=/usr
    else
        %configure --disable-static --prefix=/usr
    fi
build      : |
    %make -j1
install    : |
    %make_install

    # Symlink needed for kodi modplug binary add-on
    # Kodi is 64-bit only, so we don't care about the 32 bit version
    if [ -f $installdir/usr/lib64/libmodplug.so.1 ]; then
        pushd .
        cd $installdir/usr/lib64/
        ln -s libmodplug.so.1 libmodplug.so.0
        popd
    fi
