name       : libmodplug
homepage   : http://modplug-xmms.sourceforge.net/
version    : 0.8.8.5
release    : 4
source     :
    - http://sourceforge.net/projects/modplug-xmms/files/libmodplug/0.8.8.5/libmodplug-0.8.8.5.tar.gz : 77462d12ee99476c8645cb5511363e3906b88b33a6b54362b4dbc0f39aa2daad
license    : GPL-2.0
summary    : Library for playing MOD-like music files
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
description: |
    libmodplug is a library based on the mod rendering code fro
    m ModPlug, a popular windows mod player written by Olivier Lapicque
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-lie-about-includedir-location.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        linux32 %configure --disable-static --prefix=/usr
    else
        %configure --disable-static --prefix=/usr
    fi
build      : |
    %make -j1
install    : |
    %make_install
